services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=Demo'
      - 'MYSQL_PASSWORD=Brian256'
      - 'MYSQL_ROOT_PASSWORD=Kampala256'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3306'

  app:
    image: propertymanagmentsystem
    ports:
      - '8084:8081'
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/Demo
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: myuser
      spring.datasource.password: Brian256
    depends_on:
      - mysql
    networks:
      - default
    restart: always
#volumes:
#  todo-mysql-data: